# Generated by Django 4.2.28 on 2026-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KraRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=10)),
                ('first_name_input', models.CharField(max_length=60)),
                ('kra_full_name', models.CharField(blank=True, default='', max_length=200)),
                ('masked_name', models.CharField(blank=True, default='', max_length=200)),
                ('kra_pin', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('LOOKUP_OK', 'Lookup Ok'), ('CONFIRMED', 'Confirmed'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('RELEASED', 'Released')], default='LOOKUP_OK', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
