# Generated by Django 4.2.28 on 2026-02-10 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('STK', 'Stk'), ('MANUAL', 'Manual')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DUPLICATE', 'Duplicate')], default='PENDING', max_length=12)),
                ('amount', models.PositiveIntegerField(default=100)),
                ('till', models.CharField(default='8993804', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, default='', max_length=20, unique=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='requests_app.krarequest')),
            ],
        ),
    ]
